name: Generate 3D Profile Image
on:
  repository_dispatch:
    types: [generate-3d-profile-image]

jobs:
  build:
    runs-on: ubuntu-latest

    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "Abhishek Panthee"
          git config user.email abhishek.080bct002@tcioe.edu.np
          git add -A .
          git commit -m "Generate 3D images"
          git push